tasks:

  - name: set permissions for log directory
    init: sudo chown $(whoami):$(whoami) -R /var/log && touch /var/log/bad{node,python,golang,rust}.log
    command: exit

  - name: start the python process
    init: bash randomize_suspects.sh
    command: sleep 5 && python badlog-python.py

  - name: start the golang process
    init: go build -o badlog-golang badlog-go.go
    command: sleep 5 && ./badlog-golang

  - name: start the rust process
    init: cargo build
    command: sleep 5 && ./target/debug/badlog-rust

  - name: bad log file investigation
    command: echo "let's start the investigation!"

  #- name: delete the evidence
  #  command: sleep 5 && rm .env.suspects && exit
